/*
@doc()
This documentation is automatically generated by `terraform-docs` utility.
Every sections below should have its own introductory paragraph, go ahead and read.
*/

variable "version" {
  description = "This description is read from attribute"
}

// This description is read from associated comment
variable "az" {
  type = "list"
}

output "instance_id" {
  value = "3"
  description = "This is the instance ID"
}

// This description is associated with aws_ami data
// provider and will appear in docs
data "aws_ami" "app" {
  filter {
    name = "image-id"
    values = ["abcd-123"]
  }
}

// @doc(input)
// This is the intro paragraph of Input section.
// Comment sections are separated by an uncommented empty line.
//
// The commented empty line above means this line is part
// of intro paragraph.

// Comment groups without @doc annotation are ignored.

// This description is associated with random_pet resource.
resource "random_pet" "suffix" {
  length = 1
  keepers {
    ami_id = "abcd-123"
  }
}

// Resources have description as well.
resource "aws_instance" "app" {
   // ... attributes
}

# @doc(data-provider)
# Intro docs can appear in any order and in any file regardless of their
# position in generated documentation. The order of comments in each file
# is retained.

// This IAM policy is allows an EC2 instance to assume roles
data "aws_iam_policy_document" "allow_assume_role" {
  "statement" {
    actions = [
      "sts:AssumeRole"
    ]

    principals {
      type        = "Service"
      identifiers = [
        "ec2.amazonaws.com"
      ]
    }
  }
}

// This IAM policy allows describing all EC2 instances and their tags
data "aws_iam_policy_document" "allow_describe_tags" {
  "statement" {
    actions = [
      "ec2:DescribeInstances",
      "ec2:DescribeTags"
    ]

    resources = ["*"]
  }
}

/*
@doc(output)
This is the intro paragraph for output section.
It will be displayed on top of outputs table.
*/
